<a href="https://colab.research.google.com/github/code-dresser/Data-Science-in-Python/blob/main/Data_science_in_python_17_10_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy
import pandas
import matplotlib

# Numpy

1. Managing lists, dictionaries, sets and tuples
2. Operations on N-dimensional arrays with Numpy
3. Operations with dense or sparse arrays with Numpy and SciPy
4. Dumping and retrival of dataset
---
Numpy provides a huge range of fast and efficient ways to create and manipulate numerical data within them. While Python list can contain different types of data within single list, Numpy array **must be** homogenous. Mathematical operations that can be performed on arrays would be extremely inefficient if the data were not homogeneous.




# List, dictionaries, set and tuples

---



In [4]:
import numpy as np

*Althrough Numpy can work with all numeric types, most methods return **float** value*

### Create a list/array in Numpy

From Python list

In [6]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
my_matrix = [ [1,2,3],
              [5,6,7],
              [8,9,0]]
np.array(my_matrix)

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

Numpy does not accept unbalance matrices

In [8]:
matrix = [ [1,2,3],
              [4,5,6,7,8]]
np.array(matrix)

<ipython-input-8-c702c96dbccc>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(matrix)


array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

####From Numpy methods
Evenly space values within a given interval

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Zeros and ones

In [13]:
np.zeros(3)

array([0., 0., 0.])