<a href="https://colab.research.google.com/github/code-dresser/Data-Science-in-Python/blob/main/Data_science_in_python_17_10_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy
import pandas
import matplotlib

# Numpy

1. Managing lists, dictionaries, sets and tuples
2. Operations on N-dimensional arrays with Numpy
3. Operations with dense or sparse arrays with Numpy and SciPy
4. Dumping and retrival of dataset
---
Numpy provides a huge range of fast and efficient ways to create and manipulate numerical data within them. While Python list can contain different types of data within single list, Numpy array **must be** homogenous. Mathematical operations that can be performed on arrays would be extremely inefficient if the data were not homogeneous.




# List, dictionaries, set and tuples

---



In [6]:
import numpy as np

*Althrough Numpy can work with all numeric types, most methods return **float** value*

### Create a list/array in Numpy

From Python list

In [ ]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
my_matrix = [ [1,2,3],
              [5,6,7],
              [8,9,0]]
np.array(my_matrix)

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

Numpy does not accept unbalance matrices

In [ ]:
matrix = [ [1,2,3],
              [4,5,6,7,8]]
np.array(matrix)

<ipython-input-8-c702c96dbccc>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(matrix)


array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

####From Numpy methods
Evenly space values within a given interval

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

You can use the *arange* method with a step less than 1

In [ ]:
np.arange(0.0,1.0,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

Zeros and ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Lineary spaced

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

4 item in range 0 to 10

In [ ]:
np.linspace(0,10,50)
# from 0 to 10, 50 items

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Identity Matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 1,2

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Lesson 2

unravel_index


In [ ]:
n = np.array([[1,2,3],[9,8,6],[10,5,9]])
print(n.shape,n.min(),n.max(),n.argmin(),n.argmax())


(3, 3) 1 10 0 6


In [ ]:
np.unravel_index(n.argmax(),n.shape)

(2, 0)

Returns the index of maximum value ( 3rd row, 1st column)

In [ ]:
np.argmax(n,axis=0)

array([2, 1, 2])

Return the index of maxumum value in each column

In [ ]:
np.argmax(n,axis=1)

array([2, 0, 0])

Return the index of maximum value in each row

In [ ]:
n = np.arange(1,26)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
n.shape


(25,)

In [ ]:
n.reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

## Operation with N-dimensional arrays with Numpy


Arithmetic operations

In [13]:
arr = np.arange(2,10).reshape(2,4)
print(arr)
print()
ort = np.arange(22,30).reshape(2,4)
print(ort)

[[2 3 4 5]
 [6 7 8 9]]

[[22 23 24 25]
 [26 27 28 29]]


### Add

In [14]:
arr + ort

array([[24, 26, 28, 30],
       [32, 34, 36, 38]])

0 + 20 = 20 ,1 + 21 = 22, ... 9 + 29 = 38

In [15]:
arr + 1

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [16]:
_2by4 = np.arange(0,8).reshape(2,4)
_2by4

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
arr + _2by4

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

**ValueError:** operands could not be broadcast together with shapes (2,5) (2,4)

### Subtraction

In [ ]:
arr - ort

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

0 - 20 = -20 , 1- 21 = -20, ... ,9 - 29 = -20

In [ ]:
arr - 8

array([[-8, -7, -6, -5, -4],
       [-3, -2, -1,  0,  1]])

### Multiply

In [ ]:
arr * ort

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261]])

In [ ]:
arr * 8

array([[ 0,  8, 16, 24, 32],
       [40, 48, 56, 64, 72]])

### Division

In [ ]:
arr / ort

array([[0.        , 0.04761905, 0.09090909, 0.13043478, 0.16666667],
       [0.2       , 0.23076923, 0.25925926, 0.28571429, 0.31034483]])

In [ ]:
ort / arr

<ipython-input-35-673e90f52ebc>:1: RuntimeWarning: divide by zero encountered in divide
  ort / arr


array([[        inf, 21.        , 11.        ,  7.66666667,  6.        ],
       [ 5.        ,  4.33333333,  3.85714286,  3.5       ,  3.22222222]])

### Power

In [ ]:
arr ** 2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
arr ** ort

array([[                  0,                   1,             4194304,
                94143178827,     281474976710656],
       [ 298023223876953125, 4561031516192243712, 5059972980857283351,
                          0, 5756027422282277481]])

Bewere of the types
Operator does not check if the values exceed thier types, which in this case they do exceed the type `int` and that is why they give strange value. We can solve this problem by using bigger types i.e `float`, `double`

In [ ]:
arr = np.arange(0.,10.).reshape(2,5)
ort = np.arange(20.,30.).reshape(2,5)
arr ** ort

array([[0.00000000e+00, 1.00000000e+00, 4.19430400e+06, 9.41431788e+10,
        2.81474977e+14],
       [2.98023224e+17, 1.70581728e+20, 6.57123624e+22, 1.93428131e+25,
        4.71012870e+27]])

### Remainder

In [ ]:
arr % 2

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

## Universal function

Square root

In [ ]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

Exponant

In [ ]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

Maximum

In [ ]:
np.max(arr)

9.0

Minimum

In [ ]:
np.min(arr)

0.0

In [ ]:
np.log(ort)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383],
       [3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583]])

In [ ]:
np.average(arr)

4.5

In [ ]:
np.median(arr)

4.5

Standard deviation

In [ ]:
np.std(arr)

2.8722813232690143

### Sort

The `sort()` method is versatile and support the `quicksort`, `mergesort`, `heapsort` and `typesort`

In [ ]:
tosort = np.random.randint(1,100,1_000_000)

In [ ]:
np.sort(tosort)

array([ 1,  1,  1, ..., 99, 99, 99])

In [ ]:
np.sort(tosort,kind='heapsort')

array([ 1,  1,  1, ..., 99, 99, 99])

In [ ]:
np.sort(tosort,kind='mergesort')

array([ 1,  1,  1, ..., 99, 99, 99])

Sort by line

In [ ]:
matriz = np.array([[7,4,9],[3,4,1]])

In [ ]:
np.sort(matriz,axis=1)

array([[4, 7, 9],
       [1, 3, 4]])

Sort by column

In [ ]:
np.sort(matriz,axis=0)

array([[3, 4, 1],
       [7, 4, 9]])

### Group and filter

In [ ]:
matriz = np.random.randint(1,26,25).reshape(5,5)

In [ ]:
matriz

array([[ 4, 12, 14, 24, 24],
       [ 2, 21,  9,  7, 22],
       [14, 20,  1, 19, 15],
       [25,  6,  3, 12, 19],
       [ 5, 20, 13, 22, 24]])

Values above 5

In [ ]:
matriz[matriz >= 5]

array([12, 14, 24, 24, 21,  9,  7, 22, 14, 20, 19, 15, 25,  6, 12, 19,  5,
       20, 13, 22, 24])

This happens because ` matriz >= 5` returns binary result, possible to be compated with the indexes of the orginal `array`

In [ ]:
matriz >= 5

array([[False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

### Count

Count each occurrence of each value ( the index corresponds to the number of times it exsist in the array  and to the value

In [ ]:
m = np.random.randint(1,5,15)
np.bincount(m)

array([0, 4, 3, 5, 3])

In [ ]:
m = np.random.randint(900,1000,1000)
np.bincount(m)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

### Boolean operators

Chained

In [ ]:
n = np.array([1,1,3,4,5,5,7,8,9])
( n < 4) | ( n % 2 == 1)

array([ True,  True,  True, False,  True,  True,  True, False,  True])

In [ ]:
n[ ( n < 4 ) & ( n % 2 == 1)]

array([1, 1, 3])

### Conditionals

In [ ]:
n = n.reshape(3,3)
print(n)
print()
np.where(n < 4, 0,n)

[[1 1 3]
 [4 5 5]
 [7 8 9]]



array([[0, 0, 0],
       [4, 5, 5],
       [7, 8, 9]])

Ex 4

In [ ]:
support = np.arange(1,26).reshape(5,5)
support

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
support[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Ex 5

Get the sum of `support` array

In [ ]:
np.sum(support)

325

Ex 6

Get the sum of each column in the `support` array

In [ ]:
np.sum(support,axis=0)

array([55, 60, 65, 70, 75])

#### Week 3:


exericise 1

In [ ]:
import numpy as np
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Exercise 4

In [ ]:
support = np.arange(1,26).reshape(5,5)
support

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
support[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Exercise 5


In [ ]:
np.sum(support)

325

Exercise 6

In [ ]:
np.sum(support,axis=0)

array([55, 60, 65, 70, 75])

Exercise 7

In [ ]:
np.linspace(7,20,33)

array([ 7.     ,  7.40625,  7.8125 ,  8.21875,  8.625  ,  9.03125,
        9.4375 ,  9.84375, 10.25   , 10.65625, 11.0625 , 11.46875,
       11.875  , 12.28125, 12.6875 , 13.09375, 13.5    , 13.90625,
       14.3125 , 14.71875, 15.125  , 15.53125, 15.9375 , 16.34375,
       16.75   , 17.15625, 17.5625 , 17.96875, 18.375  , 18.78125,
       19.1875 , 19.59375, 20.     ])

Exercise 8

In [ ]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

Exercise 9

In [ ]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

Exercise 10

In [ ]:
np.random.randint(0,10,25).reshape(5,5)

array([[4, 6, 4, 0, 5],
       [3, 8, 3, 1, 6],
       [3, 0, 4, 5, 7],
       [4, 3, 9, 1, 3],
       [5, 8, 2, 5, 8]])

In [ ]:
np.random.randint(0,10,size=(5,5))

array([[9, 9, 0, 6, 3],
       [5, 8, 4, 7, 7],
       [9, 9, 0, 0, 9],
       [1, 7, 7, 4, 1],
       [8, 6, 8, 4, 5]])

Exercise 11

In [ ]:
e11 = np.array([10,1,5,2])

In [ ]:
np.argsort(e11)

array([1, 3, 2, 0])

Exercise 12

In [ ]:
 n = np.zeros(10)
 n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Exercise 13


In [ ]:
e13 = np.arange(50)
e13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
np.flip(e13)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Exercise 14

In [ ]:
e14 = np.asarray(
    [
        [0, 0, 0, 1, 0, 2, 2, 1, 2, 1],
        [1, 1, 0, 0, 0, 2, 2, 2, 2, 2],
        [2, 1, 0, 0, 2, 1, 2, 1, 0, 2],
    ]
)

In [ ]:
np.all(e14 == 0,axis = 0)

array([False, False,  True, False, False, False, False, False, False,
       False])

In [ ]:
~np.any(e14,axis=0)

array([False, False,  True, False, False, False, False, False, False,
       False])

Exercise 15

In [ ]:
e15 = np.asarray(
    [
        0.17454141,
        0.99539772,
        0.88173332,
        0.44758664,
        0.93542504,
        0.95911264,
        0.13585902,
        0.80207084,
        0.23044445,
        0.44560187,
    ])

In [ ]:
idx = [np.abs(x - 0.5) for x in e15]

In [ ]:
e15[np.argmin(idx)]

0.44758664

Exercise 16

In [ ]:
e16 = np.asarray(
    [
        [1, 0, 9, 7, 7, 0, 5, 8, 7, 0],
        [3, 8, 6, 2, 1, 9, 3, 0, 9, 1],
        [8, 1, 9, 4, 4, 7, 5, 3, 1, 2],
        [6, 8, 4, 7, 3, 1, 5, 6, 7, 4],
        [6, 9, 9, 4, 1, 7, 1, 9, 1, 0],
    ]
)

In [ ]:
 e16 - np.mean(e16,axis=1,keepdims=True)

array([[-3.4, -4.4,  4.6,  2.6,  2.6, -4.4,  0.6,  3.6,  2.6, -4.4],
       [-1.2,  3.8,  1.8, -2.2, -3.2,  4.8, -1.2, -4.2,  4.8, -3.2],
       [ 3.6, -3.4,  4.6, -0.4, -0.4,  2.6,  0.6, -1.4, -3.4, -2.4],
       [ 0.9,  2.9, -1.1,  1.9, -2.1, -4.1, -0.1,  0.9,  1.9, -1.1],
       [ 1.3,  4.3,  4.3, -0.7, -3.7,  2.3, -3.7,  4.3, -3.7, -4.7]])

In [ ]:
import numpy as np
def prime_sieve(n: int) -> np.ndarray:
    primes = np.full(n + 1, True)
    primes[0] = False
    primes[1] = False
    for i in range(2,n):
      primes[2*i::i] = False
    print(primes)
    print(np.nonzero(primes))
prime_sieve(11)

[False False  True  True False  True False  True False False False  True]
(array([ 2,  3,  5,  7, 11]),)


# Using dense and sparse matrices with NumPy and SciPy

In [ ]:
n = np.bincount([4,1000,1000,1200])

In [ ]:
def dispersion(matriz) -> np.array:
  return (matriz == 0).sum() / matriz.size

In [ ]:
dispersion(n)

0.9975020815986678

In [ ]:
a = np.array([[9,5,9],
             [9,5,8],
             [7,5,3],
             [5,3,9],
             [7,7,6]])
a

array([[9, 5, 9],
       [9, 5, 8],
       [7, 5, 3],
       [5, 3, 9],
       [7, 7, 6]])

In [ ]:
np.apply_along_axis(lambda arr: arr.min() / arr.max(),1,a)

array([0.55555556, 0.55555556, 0.42857143, 0.33333333, 0.85714286])

In [ ]:
a = np.array([[9,4,15,0,17],[16,17,8,9,0]])
a

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

In [ ]:
np.ravel(a,order="A")

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])